services:
  - type: web
    name: obie-admin
    runtime: static
    buildCommand: cd web/admin && npm install && npm run build
    staticPublishPath: web/admin/dist
    routes:
      - type: rewrite
        source: /assets/(.*)
        destination: /assets/$1
      - type: rewrite
        source: /(.*)\.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)
        destination: /$1.$2
      - type: rewrite
        source: /(.*)$
        destination: /index.html
